// <auto-generated />
namespace FirefoxPortableDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTableTaiKhoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTableTaiKhoan));
        
        string IMigrationMetadata.Id
        {
            get { return "202110140815246_Add-Table-TaiKhoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
